# Specify the DBMS
cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800
imgPath: "C:/dummyPath"
spring:
  jpa:
    show-sql: true
  profiles:
    active: dev
